repos:
  - repo: local
    hooks:
      # Prevent skipping tests
      - id: no-skip-tests
        name: No @pytest.mark.skip decorators allowed
        entry: sh -c 'if grep -r "@pytest\.mark\.skip[^_]" --include="test_*.py" tests/ 2>/dev/null | grep -v skip_ci; then echo "❌ Found @pytest.mark.skip decorators! Tests must not be skipped."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true

      # Ensure smoke tests pass
      - id: smoke-tests
        name: Run smoke tests (critical paths)
        entry: uv run pytest tests/smoke/ -v --tb=short -m smoke
        language: system
        pass_filenames: false
        stages: [manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^src/
        additional_dependencies:
          - pydantic>=2.0.0
          - types-pillow>=10.0.0
          - boto3-stubs[s3]>=1.35.0
        args: [--strict]
