name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run ruff linter
        run: uv run ruff check src/ tests/

      - name: Run ruff formatter check
        run: uv run ruff format --check src/ tests/

      - name: Run mypy type checker
        run: uv run mypy src/

      - name: Check AdCP schemas are up to date
        run: |
          uv run python scripts/generate_schemas.py
          if ! git diff --exit-code src/creative_agent/schemas_generated/; then
            echo "❌ Generated schemas are out of sync!"
            echo "Run: python scripts/generate_schemas.py"
            exit 1
          fi

      - name: Run smoke tests
        run: uv run pytest tests/smoke/ -v --no-cov -m smoke

      - name: Run schema compliance tests
        run: uv run pytest tests/schema_compliance/ -v --no-cov

      - name: Run all tests with coverage
        run: uv run pytest --cov=src/creative_agent --cov-fail-under=10 --cov-report=term-missing

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: pre-commit/action@v3.0.1
