name: Link Check

on:
  pull_request:
    paths:
      - '**.md'
  schedule:
    # Run weekly on Monday at 9am UTC to catch links that break over time
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Check all markdown files
          args: --verbose --no-progress '**/*.md'
          # Fail on broken links
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
