# generated by datamodel-codegen:
#   filename:  _schemas_v1_creative_asset-types_index_json.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field, RootModel


class AdcpAssetTypeDefinitionsRegistry(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Standardized definitions for all asset types used in AdCP creative manifests. These asset types are used when providing actual creative content that fulfills format requirements.",
            title="AdCP Asset Type Definitions Registry",
        ),
    ]
