# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_activate-signal-request_json.json

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class ActivateSignalRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    adcp_version: Annotated[
        Optional[str],
        Field(
            description="AdCP schema version for this request",
            pattern="^\\d+\\.\\d+\\.\\d+$",
        ),
    ] = "1.5.0"
    signal_agent_segment_id: Annotated[
        str, Field(description="The universal identifier for the signal to activate")
    ]
    platform: Annotated[str, Field(description="The target platform for activation")]
    account: Annotated[
        Optional[str],
        Field(
            description="Account identifier (required for account-specific activation)"
        ),
    ] = None
