# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_budget_json.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class Pacing(Enum):
    even = "even"
    asap = "asap"
    front_loaded = "front_loaded"


class Budget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[float, Field(description="Total budget amount", ge=0.0)]
    currency: Annotated[
        str,
        Field(
            description="ISO 4217 currency code",
            examples=["USD", "EUR", "GBP"],
            pattern="^[A-Z]{3}$",
        ),
    ]
    pacing: Annotated[
        Optional[Pacing], Field(description="Budget pacing strategy", title="Pacing")
    ] = None
