# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_task-status_json.json

from __future__ import annotations

from enum import Enum


class TaskStatus(Enum):
    submitted = "submitted"
    working = "working"
    input_required = "input-required"
    completed = "completed"
    canceled = "canceled"
    failed = "failed"
    rejected = "rejected"
    auth_required = "auth-required"
    unknown = "unknown"
