# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_snippet-type_json.json

from __future__ import annotations

from enum import Enum


class SnippetType(Enum):
    vast_xml = "vast_xml"
    vast_url = "vast_url"
    html = "html"
    javascript = "javascript"
    iframe = "iframe"
    daast_url = "daast_url"
