# generated by datamodel-codegen:
#   filename:  _schemas_v1_standard-formats_asset-types_index_json.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field, RootModel


class AdcpAssetTypeDefinitionsRegistry(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Standardized definitions for all asset types used in AdCP creative formats",
            title="AdCP Asset Type Definitions Registry",
        ),
    ]
