# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_html-asset_json.json

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class HtmlAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["html"]
    content: Annotated[str, Field(description="HTML content")]
    version: Annotated[
        Optional[str], Field(description="HTML version (e.g., 'HTML5')")
    ] = None
