# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_channels_json.json

from __future__ import annotations

from enum import Enum


class AdvertisingChannels(Enum):
    display = "display"
    video = "video"
    audio = "audio"
    native = "native"
    dooh = "dooh"
    ctv = "ctv"
    podcast = "podcast"
    retail = "retail"
    social = "social"
