# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_media-buy-status_json.json

from __future__ import annotations

from enum import Enum


class MediaBuyStatus(Enum):
    pending_activation = "pending_activation"
    active = "active"
    paused = "paused"
    completed = "completed"
