# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_response_json.json

from __future__ import annotations

from typing import Annotated, Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class ProtocolResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[str, Field(description="Human-readable summary")]
    context_id: Annotated[
        Optional[str], Field(description="Session continuity identifier")
    ] = None
    data: Annotated[
        Optional[Any],
        Field(
            description="AdCP task-specific response data (see individual task response schemas)"
        ),
    ] = None
