# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_list-authorized-properties-request_json.json

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Tag(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Tag to filter by (e.g., 'local_radio', 'premium_content')",
            pattern="^[a-z0-9_]+$",
        ),
    ]


class ListAuthorizedPropertiesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    adcp_version: Annotated[
        Optional[str],
        Field(
            description="AdCP schema version for this request",
            pattern="^\\d+\\.\\d+\\.\\d+$",
        ),
    ] = "1.0.0"
    tags: Annotated[
        Optional[list[Tag]],
        Field(description="Filter properties by specific tags (optional)"),
    ] = None
