# generated by datamodel-codegen:
#   filename:  _schemas_v1_creative_preview-creative-response_json.json

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class Dimensions(BaseModel):
    width: Annotated[float, Field(ge=0.0)]
    height: Annotated[float, Field(ge=0.0)]


class Embedding(BaseModel):
    recommended_sandbox: Annotated[
        Optional[str],
        Field(
            description="Recommended iframe sandbox attribute value (e.g., 'allow-scripts allow-same-origin')"
        ),
    ] = None
    requires_https: Annotated[
        Optional[bool],
        Field(description="Whether this output requires HTTPS for secure embedding"),
    ] = None
    supports_fullscreen: Annotated[
        Optional[bool],
        Field(description="Whether this output supports fullscreen mode"),
    ] = None
    csp_policy: Annotated[
        Optional[str],
        Field(description="Content Security Policy requirements for embedding"),
    ] = None


class Render(BaseModel):
    render_id: Annotated[
        str,
        Field(
            description="Unique identifier for this rendered piece within the variant"
        ),
    ]
    preview_url: Annotated[
        AnyUrl,
        Field(
            description="URL to an HTML page that renders this piece. Can be embedded in an iframe. Handles all rendering complexity internally (images, video players, audio players, interactive content, etc.)."
        ),
    ]
    role: Annotated[
        str,
        Field(
            description="Semantic role of this rendered piece. Use 'primary' for main content, 'companion' for associated banners, descriptive strings for device variants or custom roles."
        ),
    ]
    dimensions: Annotated[
        Optional[Dimensions],
        Field(
            description="Dimensions for this rendered piece. For companion ads with multiple sizes, this specifies which size this piece is."
        ),
    ] = None
    embedding: Annotated[
        Optional[Embedding],
        Field(
            description="Optional security and embedding metadata for safe iframe integration"
        ),
    ] = None


class Input(BaseModel):
    name: Annotated[str, Field(description="Human-readable name for this variant")]
    macros: Annotated[
        Optional[dict[str, str]],
        Field(description="Macro values applied to this variant"),
    ] = None
    context_description: Annotated[
        Optional[str], Field(description="Context description applied to this variant")
    ] = None


class Preview(BaseModel):
    preview_id: Annotated[
        str, Field(description="Unique identifier for this preview variant")
    ]
    renders: Annotated[
        list[Render],
        Field(
            description="Array of rendered pieces for this preview variant. Most formats render as a single piece. Companion ad formats (video + banner), multi-placement formats, and adaptive formats render as multiple pieces.",
            min_length=1,
        ),
    ]
    input: Annotated[
        Input,
        Field(
            description="The input parameters that generated this preview variant. Echoes back the request input or shows defaults used."
        ),
    ]


class PreviewCreativeResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    previews: Annotated[
        list[Preview],
        Field(
            description="Array of preview variants. Each preview corresponds to an input set from the request. If no inputs were provided, returns a single default preview.",
            min_length=1,
        ),
    ]
    interactive_url: Annotated[
        Optional[AnyUrl],
        Field(
            description="Optional URL to an interactive testing page that shows all preview variants with controls to switch between them, modify macro values, and test different scenarios."
        ),
    ] = None
    expires_at: Annotated[
        AwareDatetime, Field(description="ISO 8601 timestamp when preview links expire")
    ]
