# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_frequency-cap_json.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class FrequencyCap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    suppress_minutes: Annotated[
        float, Field(description="Minutes to suppress after impression", ge=0.0)
    ]
