# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_text-asset_json.json

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class TextAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: Annotated[str, Field(description="Text content")]
    language: Annotated[
        Optional[str], Field(description="Language code (e.g., 'en', 'es', 'fr')")
    ] = None
