# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_frequency-cap-scope_json.json

from __future__ import annotations

from enum import Enum


class FrequencyCapScope(Enum):
    package = "package"
