# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_url-asset_json.json

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class UrlAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["url"]
    url: Annotated[AnyUrl, Field(description="URL reference")]
    description: Annotated[
        Optional[str], Field(description="Description of what this URL points to")
    ] = None
