# generated by datamodel-codegen:
#   filename:  _schemas_v1_creative_asset-types_index_json.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field, RootModel


class AdcpAssetTypeRegistry(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Registry of asset types used in AdCP creative manifests. Each asset type defines the structure of actual content payloads (what you send), not requirements or constraints (which belong in format specifications).",
            title="AdCP Asset Type Registry",
        ),
    ]
