# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_package-status_json.json

from __future__ import annotations

from enum import Enum


class PackageStatus(Enum):
    draft = "draft"
    active = "active"
    paused = "paused"
    completed = "completed"
